"""empty message

Revision ID: 395c83011eff
Revises: 02316a30f9f3
Create Date: 2019-10-15 16:03:50.186254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395c83011eff'
down_revision = '02316a30f9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
